### ISSUE TITLE
[cetic/swaggerui] Documentation bug (i.e. "swagger-ui" incorrect, need to use "swaggerui" in values)

### ISSUE THREAD

**Issue by IAXES** [cetic/helm-swagger-ui#9]
**Describe the bug**

There appears to be a discrepancy between the documentation on the main page for this repo, and the values used at run time. For example, I use the following script to rapidly deploy this chart to throwaway/ephemeral clusters (thanks for making this chart by the way, as it's quite helpful):

```sh
helm repo add cetic https://cetic.github.io/helm-charts
helm repo update
helm delete swagger-demo
helm install swagger-demo cetic/swaggerui \
    --set swaggerui.jsonUrl='http://my-k8s-app.my-k8s-namespace.svc.cluster.local/v1/openapi.json' \
    --set swaggerui.server.url='http://my-dev-machine.acme.co/swagger-ingress-name/v1/'
```

The key piece is that the documentation says the value should be **`swagger-ui`**, but the chart appears to use **`swaggerui`** (i.e. without the `-` literal).

**Version of Helm and Kubernetes**:

```sh
helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

N/A.

**What happened**:

Helm installation defaults to the "petstore" example when using `--set swagger-ui ...`.

**What you expected to happen**:

In the above-noted use case, for the installation to use my user-supplied settings for `jsonUrl`.

**How to reproduce it** (as minimally and precisely as possible):

Example provided above (you would need to change the values, but you could confirm via `kubectl logs` that the user-supplied parameters are ignored if using `swagger-ui` versus `swaggerui`).

**Anything else we need to know**:

It would be nice to have some examples (i.e. shell one-liners using `set` for all the values, plus a sample `values.overrides.yaml` example for configuring the ingress). For some reason, I can't get the ingress going, and have to manually install (via `kubectl apply -f ...`) my own ingress definition (below). Maybe some chart rendering quirk.

```yaml
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sample-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # To allow certain security features for SwaggerUI to be ignored for
    # testing purposes.
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: swagger-demo-swaggerui
          servicePort: 8080
        path: /swagger-ingress-name/(.*)
```
